server.port: 8089

logging:
  level:
    ROOT: INFO
    com.mfptps.appdgessddi: DEBUG

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate.ddl-auto: update
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
      additional-exclude: .h2.server.properties
    livereload:
      enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./target/h2db/db/dgess;DB_CLOSE_DELAY=-1
    username: dgess
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  h2:
    console:
      enable: true
      path: /h2-console